version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    mem_limit: 2g
    cpus: 1

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
      - ../machine_learning/models:/app/machine_learning/models
    mem_limit: 3g
    cpus: 1
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///credit_score.db
      - SECRET_KEY=your-secret-key
      - JWT_SECRET_KEY=your-jwt-secret-key

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: credit_score_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    mem_limit: 1g
    cpus: 0.5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: